/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Stub for Convex generated API module.
 * Auto-generated by `npx convex dev` in a real deployment.
 *
 * Provides typed references to all Convex functions.
 * These stubs use `any` to allow compilation without a backend.
 */

export const api: any = new Proxy(
  {},
  {
    get(_target, prop) {
      return new Proxy(
        {},
        {
          get(_target2, prop2) {
            return `${String(prop)}.${String(prop2)}`;
          },
        }
      );
    },
  }
);

export const internal: any = new Proxy(
  {},
  {
    get(_target, prop) {
      return new Proxy(
        {},
        {
          get(_target2, prop2) {
            return `${String(prop)}.${String(prop2)}`;
          },
        }
      );
    },
  }
);
