/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Stub for Convex generated API module.
 * Auto-generated by `npx convex dev` in a real deployment.
 *
 * Uses a recursive proxy so arbitrarily deep paths like
 * api.core.queries.getCurrentUser resolve correctly.
 */

function createRecursiveProxy(path: string[] = []): any {
  return new Proxy(() => {}, {
    get(_target, prop) {
      if (typeof prop === "string") {
        return createRecursiveProxy([...path, prop]);
      }
      return undefined;
    },
    apply() {
      return path.join(".");
    },
  });
}

export const api: any = createRecursiveProxy();
export const internal: any = createRecursiveProxy();
