/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Stub for Convex generated data model.
 * Auto-generated by `npx convex dev` in a real deployment.
 */

import type { GenericDataModel } from "convex/server";

export type DataModel = GenericDataModel;
