/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Stub for Convex generated server module.
 * Auto-generated by `npx convex dev` in a real deployment.
 * These stubs allow TypeScript compilation without a running Convex backend.
 * They throw at runtime to prevent accidental use in production.
 */

type FunctionBuilder = (opts: {
  args?: any;
  handler: (ctx: any, args: any) => any;
}) => any;

type HttpActionBuilder = (
  handler: (ctx: any, request: Request) => Promise<Response>
) => any;

function createStubUsageError(apiName: string): Error {
  return new Error(
    `Convex generated server stub invoked via "${apiName}". ` +
      `Run "npx convex dev" to generate real server bindings.`
  );
}

function createFunctionBuilder(apiName: string): FunctionBuilder {
  return (_opts) => {
    return () => {
      throw createStubUsageError(apiName);
    };
  };
}

export const query: FunctionBuilder = createFunctionBuilder("query");
export const mutation: FunctionBuilder = createFunctionBuilder("mutation");
export const action: FunctionBuilder = createFunctionBuilder("action");
export const internalQuery: FunctionBuilder =
  createFunctionBuilder("internalQuery");
export const internalMutation: FunctionBuilder =
  createFunctionBuilder("internalMutation");
export const internalAction: FunctionBuilder =
  createFunctionBuilder("internalAction");
export const httpAction: HttpActionBuilder = (_handler) => {
  return async () => {
    throw createStubUsageError("httpAction");
  };
};
