/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Stub for Convex generated server module.
 * Auto-generated by `npx convex dev` in a real deployment.
 * These stubs allow TypeScript compilation without a running Convex backend.
 */

type FunctionBuilder = (opts: {
  args?: any;
  handler: (ctx: any, args: any) => any;
}) => any;

type HttpActionBuilder = (
  handler: (ctx: any, request: Request) => Promise<Response>
) => any;

export const query: FunctionBuilder = (opts) => opts;
export const mutation: FunctionBuilder = (opts) => opts;
export const action: FunctionBuilder = (opts) => opts;
export const internalQuery: FunctionBuilder = (opts) => opts;
export const internalMutation: FunctionBuilder = (opts) => opts;
export const internalAction: FunctionBuilder = (opts) => opts;
export const httpAction: HttpActionBuilder = (handler) => handler;
